version: '3.9'
services:
  mongo:
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INIT_PW
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db_data:/data/db
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INIT_PW
      ME_CONFIG_MONGODB_URL: "mongodb://root:${MONGO_INIT_PW}@mongo:27017/"

volumes:
  db_data:
