apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-boostrap
  name: fastapi-boostrap-svc
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: fastapi-boostrap
